duplicated action

diff --git a/.github/actions/style/action.yml b/.github/actions/style/action.yml
--- a/.github/actions/style/action.yml
+++ b/.github/actions/style/action.yml
@@ -1,41 +1,42 @@
-name: "Doc check"
-description: "Code documentation generation with Doxygen"
+name: "Style check"
+description: "Style check using clang-format"
 
 runs:
   using: "composite"
   steps:
-    - name: "Run doxygen command"
+    - name: "Run clang-format"
       shell: bash
       run: |
-          # We only make check, not changes
-          DOX_CONF_FILE=$(pwd)/Doxyfile
+        # We only make check, not changes
+        # Use the find command with the variable
+        PROJECT_PATH=$(pwd)
 
-          # Modifying Doxygen configuration file
-          {
-              cat $DOX_CONF_FILE
-              echo "INPUT" = $(pwd)/src $(pwd)/include $(pwd)/lib
-          } > $DOX_CONF_FILE
+        echo $PROJECT_PATH
 
-          # Generate documentation
-          # ToDo: Add documentation about this command and describe better
-          sudo dot -c
+        # Find all source files and save their paths to a variable
+        SOURCE_FILES=$(find $PROJECT_PATH/src -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
+        SOURCE_FILES+=$(find $PROJECT_PATH/include -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
+        SOURCE_FILES+=$(find $PROJECT_PATH/lib -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
 
-          ERROR_FILE_FLAG=$(pwd)/dox_errors.txt
+        ERROR_FILE_FLAG=$PROJECT_PATH/clang-format_errors.txt
 
-          # Run doxygen tool using it's configuration file and save errors to a file
-          DOXYGEN_COMMAND=$(doxygen -s $DOX_CONF_FILE) > $ERROR_FILE_FLAG
+        # Run the clang-format tool and save errors to a file
+        CLANG_COMMAND=$(clang-format -i $SOURCE_FILES) > ${ERROR_FILE_FLAG}
 
-          if [ -s $ERROR_FILE_FLAG ]; then
-              echo "Error: There are some files that are not documented correctly"
-              exit 1
-          else
-              echo "All files are documented correctly. Niiiceee"
-              exit 0
-          fi
+        echo "Running: clang-format -i $SOURCE_FILES"
+
+        if [ -s $ERROR_FILE_FLAG ]; then
+            echo "Error: There are some files that are not formatted correctly"
+            exit 1
+        else
+            echo "All files are formatted correctly. Niiiceee"
+            exit 0
+        fi
+
     # Upload errors as an artifact, when failed
     - uses: actions/upload-artifact@v3
       if: failure()
       with:
-        name: Doxygen errors!!!
-        path: $(pwd)/dox_errors.txt
+        name: Clang-format errors!!!
+        path: $PROJECT_PATH/clang-format_errors.txt
         retention-days: 1
